### PR TITLE
Change back end to use NodeJs instead php

### PR DESCRIPTION
**Pull request by renancarvalho**
This pull request changes all the server side code, removes php stuff, replaces bower for NPM and also uses backbone events instead of JQuery promises.

The main Idea of this pull request is to make the server side code easier, and to use events (Backbone way) instead of JQuery promises.

### CODE REVIEW

**Comment by chiefGui** [comment]
JavaScript is love. JavaScript is life.

**Comment by renancarvalho** [comment]
@zigolis ^

**Comment by zigolis** [comment]
@renancarvalho I changed some calls and files, when you have a free time we may talk about the next examples, anyway I'm merging the branches right now!

**Comment by renancarvalho** [comment]
I took a look dude, looks good 
:+1:

**Pull request merged**
